name: Java CI with Maven and Docker

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn -s nexus-settings.xml clean deploy --batch-mode  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


